### ISSUE TITLE
SAAS-Website 

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/saas-website#1]
Issue to notify the work in progress on the SAAS-Website.
@muxlowc

**Comment by muxlowc** [comment]
@VanshitaGandhi thanks!

**Comment by VanshitaGandhi** [comment]
Hi, 
I needed help with 2 things:

1) A Markbot error
<img width="601" alt="Screenshot 2020-04-19 at 11 09 53 PM" src="https://user-images.githubusercontent.com/55109487/79710497-26bdd580-8293-11ea-879b-14030659486e.png">

2)Positioning and alignment of text on the banner of the home page

The code is committed, pushed and up-to-date.

@muxlowc @HannahDelaney

**Comment by HannahDelaney** [comment]
Hey Vanshita!

The markbot issue is likely because you need to have links in those areas of the page (note, this error is for the sign-up page). Since websites are meant to link you to places where you can continue viewing content, or in this case, sign up or pay money, if there are no links then the site can't achieve it's base function. That's why that error appears.

What do you want the banner text to do?

**Comment by VanshitaGandhi** [comment]
Aligning the text vertically on the banner @HannahDelaney
